server:
  port: 8080
  servlet:
    session:
      timeout: 60m

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/planfit_db?serverTimezone=Asia/Seoul
    username: planfit_user
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # ?? ?? update / ??? none ?? validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
jwt:
  secret: thisIsASecretKeyWithAtLeast32CharactersLong!!