server:
  port: 8080
  servlet:
    session:
      timeout: 60m

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/planfit_db?serverTimezone=Asia/Seoul
    username: planfit_user
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.project.PlanFit.comment.dto
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    jdbc-type-for-null: 'NULL'

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
jwt:
  secret: thisIsASecretKeyWithAtLeast32CharactersLong!!

file:
  base-dir: ./uploads     # 실제 쓰기 가능한 경로
  max-size: 104857600
  allowed-ext: [jpg,jpeg,png,gif,webp,pdf,ppt,pptx,doc,docx,xls,xlsx,hwp,hwpx,zip]